[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoEnergyIO = "3b1dd628-313a-45bb-9d8d-8f3c48dcb5d4"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
HYPRE = "b5ffcf37-a2bd-41ab-a3da-4bd9bc8ad771"
Jutul = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
JutulDarcy = "82210473-ab04-4dce-b31b-11573c4f8e0a"
LBFGSB = "5be7bae1-8223-5378-bac3-9e7378a2f6e6"
LayeredLayouts = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MultiComponentFlash = "35e5bd01-9722-4017-9deb-64a5d32478ff"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
