[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JutulDarcy = "82210473-ab04-4dce-b31b-11573c4f8e0a"
Jutul = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
